/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ServiceListingInput = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Nat,
});
export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Status = IDL.Variant({
  'cancelled' : IDL.Null,
  'published' : IDL.Null,
  'draft' : IDL.Null,
});
export const StaffRole = IDL.Variant({
  'admin' : IDL.Null,
  'eventManager' : IDL.Null,
  'gateStaff' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'customer' : IDL.Null,
  'staff' : IDL.Null,
  'vendor' : IDL.Null,
});
export const BookingStatus = IDL.Variant({
  'new' : IDL.Null,
  'cancelled' : IDL.Null,
  'reviewed' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Booking = IDL.Record({
  'id' : IDL.Nat,
  'status' : BookingStatus,
  'serviceType' : IDL.Text,
  'city' : IDL.Text,
  'date' : IDL.Int,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'message' : IDL.Text,
  'phone' : IDL.Text,
});
export const EventBooking = IDL.Record({
  'id' : IDL.Nat,
  'status' : BookingStatus,
  'eventId' : IDL.Nat,
  'ticketCategory' : IDL.Text,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'message' : IDL.Text,
  'quantity' : IDL.Nat,
  'phone' : IDL.Text,
  'eventName' : IDL.Text,
});
export const Event = IDL.Record({
  'id' : IDL.Nat,
  'status' : Status,
  'subCategory' : IDL.Text,
  'duration' : IDL.Text,
  'country' : IDL.Text,
  'venue' : IDL.Text,
  'city' : IDL.Text,
  'date' : IDL.Int,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'time' : IDL.Text,
  'description' : IDL.Text,
  'state' : IDL.Text,
  'posterUrl' : IDL.Text,
  'category' : IDL.Text,
  'bannerUrl' : IDL.Text,
  'ageLimit' : IDL.Nat,
});
export const ListingStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const Listing = IDL.Record({
  'id' : IDL.Nat,
  'status' : ListingStatus,
  'title' : IDL.Text,
  'city' : IDL.Text,
  'createdAt' : IDL.Int,
  'submittedBy' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Nat,
  'contactPhone' : IDL.Text,
});
export const ServiceListing = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'createdAt' : IDL.Int,
  'vendorPrincipal' : IDL.Principal,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Nat,
});
export const StaffStatus = IDL.Variant({
  'active' : IDL.Null,
  'inactive' : IDL.Null,
});
export const StaffAccount = IDL.Record({
  'id' : IDL.Nat,
  'status' : StaffStatus,
  'username' : IDL.Text,
  'createdAt' : IDL.Int,
  'role' : StaffRole,
  'passwordHash' : IDL.Text,
});
export const UserStatus = IDL.Variant({
  'active' : IDL.Null,
  'inactive' : IDL.Null,
});
export const User = IDL.Record({
  'id' : IDL.Nat,
  'status' : UserStatus,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'role' : UserRole,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const ApplicationStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const VendorApplication = IDL.Record({
  'id' : IDL.Nat,
  'status' : ApplicationStatus,
  'serviceCategory' : IDL.Text,
  'principal' : IDL.Principal,
  'ownerName' : IDL.Text,
  'city' : IDL.Text,
  'businessName' : IDL.Text,
  'submittedAt' : IDL.Int,
  'description' : IDL.Text,
  'reviewedAt' : IDL.Opt(IDL.Int),
  'email' : IDL.Text,
  'phone' : IDL.Text,
  'portfolioImages' : IDL.Vec(IDL.Text),
});
export const VendorStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
  'suspended' : IDL.Null,
});
export const Vendor = IDL.Record({
  'id' : IDL.Nat,
  'status' : VendorStatus,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'businessName' : IDL.Text,
  'email' : IDL.Text,
  'experience' : IDL.Nat,
  'phone' : IDL.Text,
  'services' : IDL.Text,
});
export const Analytics = IDL.Record({
  'totalEvents' : IDL.Nat,
  'totalBookings' : IDL.Nat,
  'totalListings' : IDL.Nat,
  'totalUsers' : IDL.Nat,
  'recentBookings' : IDL.Vec(Booking),
  'totalVendors' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const TicketCategory = IDL.Record({
  'id' : IDL.Nat,
  'eventId' : IDL.Nat,
  'availableQty' : IDL.Nat,
  'name' : IDL.Text,
  'price' : IDL.Nat,
});
export const StaffSession = IDL.Record({
  'username' : IDL.Text,
  'staffId' : IDL.Nat,
  'role' : StaffRole,
});
export const StaffLoginResult = IDL.Variant({
  'ok' : StaffSession,
  'err' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const PortfolioImageInput = IDL.Record({
  'title' : IDL.Opt(IDL.Text),
  'file' : ExternalBlob,
  'size' : IDL.Nat,
  'vendorPrincipal' : IDL.Opt(IDL.Principal),
  'mimeType' : IDL.Text,
  'description' : IDL.Opt(IDL.Text),
  'filename' : IDL.Text,
  'vendorId' : IDL.Opt(IDL.Nat),
  'category' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addServiceListing' : IDL.Func([ServiceListingInput], [IDL.Nat], []),
  'addTicketCategory' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Nat, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'createBookingRequest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Int, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createEvent' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Int,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        Status,
      ],
      [IDL.Nat],
      [],
    ),
  'createEventBooking' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'createListing' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createStaffAccount' : IDL.Func(
      [IDL.Text, IDL.Text, StaffRole],
      [IDL.Nat],
      [],
    ),
  'createUser' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, UserRole],
      [IDL.Nat],
      [],
    ),
  'createVendor' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'deleteEvent' : IDL.Func([IDL.Nat], [], []),
  'deletePortfolioImage' : IDL.Func([IDL.Nat], [], []),
  'deleteServiceListing' : IDL.Func([IDL.Nat], [], []),
  'deleteStaffAccount' : IDL.Func([IDL.Nat], [], []),
  'deleteTicketCategory' : IDL.Func([IDL.Nat], [], []),
  'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getAllEventBookings' : IDL.Func([], [IDL.Vec(EventBooking)], ['query']),
  'getAllEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'getAllListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
  'getAllServiceListings' : IDL.Func([], [IDL.Vec(ServiceListing)], ['query']),
  'getAllStaffAccounts' : IDL.Func([], [IDL.Vec(StaffAccount)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'getAllVendorApplications' : IDL.Func(
      [],
      [IDL.Vec(VendorApplication)],
      ['query'],
    ),
  'getAllVendors' : IDL.Func([], [IDL.Vec(Vendor)], ['query']),
  'getAnalytics' : IDL.Func([], [Analytics], ['query']),
  'getApprovedVendors' : IDL.Func([], [IDL.Vec(VendorApplication)], ['query']),
  'getBooking' : IDL.Func([IDL.Nat], [IDL.Opt(Booking)], ['query']),
  'getBookingsByCity' : IDL.Func([IDL.Text], [IDL.Vec(Booking)], ['query']),
  'getBookingsByDateRange' : IDL.Func(
      [IDL.Int, IDL.Int],
      [IDL.Vec(Booking)],
      ['query'],
    ),
  'getBookingsByServiceType' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Booking)],
      ['query'],
    ),
  'getBookingsByStatus' : IDL.Func(
      [BookingStatus],
      [IDL.Vec(Booking)],
      ['query'],
    ),
  'getBookingsForMyVendor' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getConfirmedBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getEvent' : IDL.Func([IDL.Nat], [IDL.Opt(Event)], ['query']),
  'getEventBookingsByEvent' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(EventBooking)],
      ['query'],
    ),
  'getListing' : IDL.Func([IDL.Nat], [IDL.Opt(Listing)], ['query']),
  'getListingsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Listing)], ['query']),
  'getListingsByCity' : IDL.Func([IDL.Text], [IDL.Vec(Listing)], ['query']),
  'getMyServiceListings' : IDL.Func([], [IDL.Vec(ServiceListing)], ['query']),
  'getMyVendorApplication' : IDL.Func(
      [],
      [IDL.Opt(VendorApplication)],
      ['query'],
    ),
  'getNewBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getPublicApprovedVendors' : IDL.Func(
      [],
      [IDL.Vec(VendorApplication)],
      ['query'],
    ),
  'getPublicEventsByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Event)],
      ['query'],
    ),
  'getPublicEventsBySubCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Event)],
      ['query'],
    ),
  'getPublicListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
  'getPublicVendorsByServices' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Vendor)],
      ['query'],
    ),
  'getPublishedEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'getPublishedVendors' : IDL.Func([], [IDL.Vec(Vendor)], ['query']),
  'getTicketCategoriesByEvent' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(TicketCategory)],
      ['query'],
    ),
  'getUpcomingEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'getUser' : IDL.Func([IDL.Nat], [IDL.Opt(User)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUsersByRole' : IDL.Func([UserRole], [IDL.Vec(User)], ['query']),
  'getVendor' : IDL.Func([IDL.Nat], [IDL.Opt(Vendor)], ['query']),
  'getVendorApplication' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(VendorApplication)],
      ['query'],
    ),
  'getVendorsByCity' : IDL.Func([IDL.Text], [IDL.Vec(Vendor)], ['query']),
  'initDefaultStaffAccount' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'reviewVendorApplication' : IDL.Func([IDL.Nat, ApplicationStatus], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'staffLogin' : IDL.Func([IDL.Text, IDL.Text], [StaffLoginResult], []),
  'submitVendorApplication' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
      ],
      [IDL.Nat],
      [],
    ),
  'updateBookingStatus' : IDL.Func([IDL.Nat, BookingStatus], [], []),
  'updateEvent' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Int,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        Status,
      ],
      [],
      [],
    ),
  'updateEventBookingStatus' : IDL.Func([IDL.Nat, BookingStatus], [], []),
  'updateListingStatus' : IDL.Func([IDL.Nat, ListingStatus], [], []),
  'updateMyVendorApplication' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
      ],
      [],
      [],
    ),
  'updateServiceListing' : IDL.Func([IDL.Nat, ServiceListingInput], [], []),
  'updateStaffAccountRole' : IDL.Func([IDL.Nat, StaffRole], [], []),
  'updateStaffAccountStatus' : IDL.Func([IDL.Nat, StaffStatus], [], []),
  'updateUser' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, UserRole],
      [],
      [],
    ),
  'updateUserStatus' : IDL.Func([IDL.Nat, UserStatus], [], []),
  'updateVendor' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'updateVendorApplicationStatus' : IDL.Func(
      [IDL.Nat, ApplicationStatus],
      [],
      [],
    ),
  'updateVendorStatus' : IDL.Func([IDL.Nat, VendorStatus], [], []),
  'uploadPortfolioImage' : IDL.Func([PortfolioImageInput], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ServiceListingInput = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Nat,
  });
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Status = IDL.Variant({
    'cancelled' : IDL.Null,
    'published' : IDL.Null,
    'draft' : IDL.Null,
  });
  const StaffRole = IDL.Variant({
    'admin' : IDL.Null,
    'eventManager' : IDL.Null,
    'gateStaff' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'customer' : IDL.Null,
    'staff' : IDL.Null,
    'vendor' : IDL.Null,
  });
  const BookingStatus = IDL.Variant({
    'new' : IDL.Null,
    'cancelled' : IDL.Null,
    'reviewed' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Booking = IDL.Record({
    'id' : IDL.Nat,
    'status' : BookingStatus,
    'serviceType' : IDL.Text,
    'city' : IDL.Text,
    'date' : IDL.Int,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'message' : IDL.Text,
    'phone' : IDL.Text,
  });
  const EventBooking = IDL.Record({
    'id' : IDL.Nat,
    'status' : BookingStatus,
    'eventId' : IDL.Nat,
    'ticketCategory' : IDL.Text,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'message' : IDL.Text,
    'quantity' : IDL.Nat,
    'phone' : IDL.Text,
    'eventName' : IDL.Text,
  });
  const Event = IDL.Record({
    'id' : IDL.Nat,
    'status' : Status,
    'subCategory' : IDL.Text,
    'duration' : IDL.Text,
    'country' : IDL.Text,
    'venue' : IDL.Text,
    'city' : IDL.Text,
    'date' : IDL.Int,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'time' : IDL.Text,
    'description' : IDL.Text,
    'state' : IDL.Text,
    'posterUrl' : IDL.Text,
    'category' : IDL.Text,
    'bannerUrl' : IDL.Text,
    'ageLimit' : IDL.Nat,
  });
  const ListingStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const Listing = IDL.Record({
    'id' : IDL.Nat,
    'status' : ListingStatus,
    'title' : IDL.Text,
    'city' : IDL.Text,
    'createdAt' : IDL.Int,
    'submittedBy' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Nat,
    'contactPhone' : IDL.Text,
  });
  const ServiceListing = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'createdAt' : IDL.Int,
    'vendorPrincipal' : IDL.Principal,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Nat,
  });
  const StaffStatus = IDL.Variant({
    'active' : IDL.Null,
    'inactive' : IDL.Null,
  });
  const StaffAccount = IDL.Record({
    'id' : IDL.Nat,
    'status' : StaffStatus,
    'username' : IDL.Text,
    'createdAt' : IDL.Int,
    'role' : StaffRole,
    'passwordHash' : IDL.Text,
  });
  const UserStatus = IDL.Variant({
    'active' : IDL.Null,
    'inactive' : IDL.Null,
  });
  const User = IDL.Record({
    'id' : IDL.Nat,
    'status' : UserStatus,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'role' : UserRole,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const ApplicationStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const VendorApplication = IDL.Record({
    'id' : IDL.Nat,
    'status' : ApplicationStatus,
    'serviceCategory' : IDL.Text,
    'principal' : IDL.Principal,
    'ownerName' : IDL.Text,
    'city' : IDL.Text,
    'businessName' : IDL.Text,
    'submittedAt' : IDL.Int,
    'description' : IDL.Text,
    'reviewedAt' : IDL.Opt(IDL.Int),
    'email' : IDL.Text,
    'phone' : IDL.Text,
    'portfolioImages' : IDL.Vec(IDL.Text),
  });
  const VendorStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
    'suspended' : IDL.Null,
  });
  const Vendor = IDL.Record({
    'id' : IDL.Nat,
    'status' : VendorStatus,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'businessName' : IDL.Text,
    'email' : IDL.Text,
    'experience' : IDL.Nat,
    'phone' : IDL.Text,
    'services' : IDL.Text,
  });
  const Analytics = IDL.Record({
    'totalEvents' : IDL.Nat,
    'totalBookings' : IDL.Nat,
    'totalListings' : IDL.Nat,
    'totalUsers' : IDL.Nat,
    'recentBookings' : IDL.Vec(Booking),
    'totalVendors' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const TicketCategory = IDL.Record({
    'id' : IDL.Nat,
    'eventId' : IDL.Nat,
    'availableQty' : IDL.Nat,
    'name' : IDL.Text,
    'price' : IDL.Nat,
  });
  const StaffSession = IDL.Record({
    'username' : IDL.Text,
    'staffId' : IDL.Nat,
    'role' : StaffRole,
  });
  const StaffLoginResult = IDL.Variant({
    'ok' : StaffSession,
    'err' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const PortfolioImageInput = IDL.Record({
    'title' : IDL.Opt(IDL.Text),
    'file' : ExternalBlob,
    'size' : IDL.Nat,
    'vendorPrincipal' : IDL.Opt(IDL.Principal),
    'mimeType' : IDL.Text,
    'description' : IDL.Opt(IDL.Text),
    'filename' : IDL.Text,
    'vendorId' : IDL.Opt(IDL.Nat),
    'category' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addServiceListing' : IDL.Func([ServiceListingInput], [IDL.Nat], []),
    'addTicketCategory' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Nat, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'createBookingRequest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Int, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createEvent' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Int,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          Status,
        ],
        [IDL.Nat],
        [],
      ),
    'createEventBooking' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'createListing' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createStaffAccount' : IDL.Func(
        [IDL.Text, IDL.Text, StaffRole],
        [IDL.Nat],
        [],
      ),
    'createUser' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, UserRole],
        [IDL.Nat],
        [],
      ),
    'createVendor' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'deleteEvent' : IDL.Func([IDL.Nat], [], []),
    'deletePortfolioImage' : IDL.Func([IDL.Nat], [], []),
    'deleteServiceListing' : IDL.Func([IDL.Nat], [], []),
    'deleteStaffAccount' : IDL.Func([IDL.Nat], [], []),
    'deleteTicketCategory' : IDL.Func([IDL.Nat], [], []),
    'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getAllEventBookings' : IDL.Func([], [IDL.Vec(EventBooking)], ['query']),
    'getAllEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'getAllListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
    'getAllServiceListings' : IDL.Func(
        [],
        [IDL.Vec(ServiceListing)],
        ['query'],
      ),
    'getAllStaffAccounts' : IDL.Func([], [IDL.Vec(StaffAccount)], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'getAllVendorApplications' : IDL.Func(
        [],
        [IDL.Vec(VendorApplication)],
        ['query'],
      ),
    'getAllVendors' : IDL.Func([], [IDL.Vec(Vendor)], ['query']),
    'getAnalytics' : IDL.Func([], [Analytics], ['query']),
    'getApprovedVendors' : IDL.Func(
        [],
        [IDL.Vec(VendorApplication)],
        ['query'],
      ),
    'getBooking' : IDL.Func([IDL.Nat], [IDL.Opt(Booking)], ['query']),
    'getBookingsByCity' : IDL.Func([IDL.Text], [IDL.Vec(Booking)], ['query']),
    'getBookingsByDateRange' : IDL.Func(
        [IDL.Int, IDL.Int],
        [IDL.Vec(Booking)],
        ['query'],
      ),
    'getBookingsByServiceType' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Booking)],
        ['query'],
      ),
    'getBookingsByStatus' : IDL.Func(
        [BookingStatus],
        [IDL.Vec(Booking)],
        ['query'],
      ),
    'getBookingsForMyVendor' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getConfirmedBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getEvent' : IDL.Func([IDL.Nat], [IDL.Opt(Event)], ['query']),
    'getEventBookingsByEvent' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(EventBooking)],
        ['query'],
      ),
    'getListing' : IDL.Func([IDL.Nat], [IDL.Opt(Listing)], ['query']),
    'getListingsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Listing)],
        ['query'],
      ),
    'getListingsByCity' : IDL.Func([IDL.Text], [IDL.Vec(Listing)], ['query']),
    'getMyServiceListings' : IDL.Func([], [IDL.Vec(ServiceListing)], ['query']),
    'getMyVendorApplication' : IDL.Func(
        [],
        [IDL.Opt(VendorApplication)],
        ['query'],
      ),
    'getNewBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getPublicApprovedVendors' : IDL.Func(
        [],
        [IDL.Vec(VendorApplication)],
        ['query'],
      ),
    'getPublicEventsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Event)],
        ['query'],
      ),
    'getPublicEventsBySubCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Event)],
        ['query'],
      ),
    'getPublicListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
    'getPublicVendorsByServices' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Vendor)],
        ['query'],
      ),
    'getPublishedEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'getPublishedVendors' : IDL.Func([], [IDL.Vec(Vendor)], ['query']),
    'getTicketCategoriesByEvent' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(TicketCategory)],
        ['query'],
      ),
    'getUpcomingEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'getUser' : IDL.Func([IDL.Nat], [IDL.Opt(User)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUsersByRole' : IDL.Func([UserRole], [IDL.Vec(User)], ['query']),
    'getVendor' : IDL.Func([IDL.Nat], [IDL.Opt(Vendor)], ['query']),
    'getVendorApplication' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(VendorApplication)],
        ['query'],
      ),
    'getVendorsByCity' : IDL.Func([IDL.Text], [IDL.Vec(Vendor)], ['query']),
    'initDefaultStaffAccount' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'reviewVendorApplication' : IDL.Func([IDL.Nat, ApplicationStatus], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'staffLogin' : IDL.Func([IDL.Text, IDL.Text], [StaffLoginResult], []),
    'submitVendorApplication' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
        ],
        [IDL.Nat],
        [],
      ),
    'updateBookingStatus' : IDL.Func([IDL.Nat, BookingStatus], [], []),
    'updateEvent' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Int,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          Status,
        ],
        [],
        [],
      ),
    'updateEventBookingStatus' : IDL.Func([IDL.Nat, BookingStatus], [], []),
    'updateListingStatus' : IDL.Func([IDL.Nat, ListingStatus], [], []),
    'updateMyVendorApplication' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
        ],
        [],
        [],
      ),
    'updateServiceListing' : IDL.Func([IDL.Nat, ServiceListingInput], [], []),
    'updateStaffAccountRole' : IDL.Func([IDL.Nat, StaffRole], [], []),
    'updateStaffAccountStatus' : IDL.Func([IDL.Nat, StaffStatus], [], []),
    'updateUser' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, UserRole],
        [],
        [],
      ),
    'updateUserStatus' : IDL.Func([IDL.Nat, UserStatus], [], []),
    'updateVendor' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'updateVendorApplicationStatus' : IDL.Func(
        [IDL.Nat, ApplicationStatus],
        [],
        [],
      ),
    'updateVendorStatus' : IDL.Func([IDL.Nat, VendorStatus], [], []),
    'uploadPortfolioImage' : IDL.Func([PortfolioImageInput], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };