/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const RoomType = IDL.Record({
  'pricePerNight' : IDL.Nat,
  'name' : IDL.Text,
});
export const TransactionStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'failed' : IDL.Null,
});
export const TransportType = IDL.Variant({
  'bus' : IDL.Null,
  'car' : IDL.Null,
  'train' : IDL.Null,
  'flight' : IDL.Null,
  'helicopter' : IDL.Null,
  'cruise' : IDL.Null,
});
export const BookingStatus = IDL.Variant({
  'new' : IDL.Null,
  'cancelled' : IDL.Null,
  'reviewed' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const HotelBooking = IDL.Record({
  'id' : IDL.Nat,
  'status' : BookingStatus,
  'paymentStatus' : TransactionStatus,
  'hotelName' : IDL.Text,
  'pricePerNight' : IDL.Nat,
  'createdAt' : IDL.Int,
  'hotelId' : IDL.Nat,
  'checkInDate' : IDL.Int,
  'guestName' : IDL.Text,
  'guestEmail' : IDL.Text,
  'totalAmount' : IDL.Nat,
  'checkOutDate' : IDL.Int,
  'guestPhone' : IDL.Text,
  'numberOfNights' : IDL.Nat,
  'roomType' : IDL.Text,
});
export const Hotel = IDL.Record({
  'id' : IDL.Nat,
  'roomTypes' : IDL.Vec(RoomType),
  'photoUrls' : IDL.Vec(IDL.Text),
  'city' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'amenities' : IDL.Vec(IDL.Text),
  'address' : IDL.Text,
});
export const PaymentTransaction = IDL.Record({
  'id' : IDL.Nat,
  'status' : TransactionStatus,
  'paymentMethod' : IDL.Text,
  'bookingId' : IDL.Nat,
  'timestamp' : IDL.Int,
  'amount' : IDL.Nat,
  'transactionId' : IDL.Text,
});
export const TransportBooking = IDL.Record({
  'id' : IDL.Nat,
  'status' : BookingStatus,
  'paymentStatus' : TransactionStatus,
  'bookedBy' : IDL.Principal,
  'transportId' : IDL.Nat,
  'city' : IDL.Text,
  'createdAt' : IDL.Int,
  'operatorName' : IDL.Text,
  'passengerName' : IDL.Text,
  'seats' : IDL.Nat,
  'passengerEmail' : IDL.Text,
  'totalAmount' : IDL.Nat,
  'travelDate' : IDL.Int,
  'transportName' : IDL.Text,
  'transportType' : IDL.Text,
  'passengerPhone' : IDL.Text,
  'route' : IDL.Text,
});
export const TransportOption = IDL.Record({
  'id' : IDL.Nat,
  'photoUrls' : IDL.Vec(IDL.Text),
  'city' : IDL.Text,
  'createdAt' : IDL.Int,
  'operatorName' : IDL.Text,
  'availableSeats' : IDL.Nat,
  'transportType' : TransportType,
  'price' : IDL.Nat,
  'route' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createHotel' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(RoomType),
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
      ],
      [IDL.Nat],
      [],
    ),
  'createHotelBooking' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Int,
        IDL.Int,
        IDL.Nat,
        IDL.Nat,
      ],
      [IDL.Nat],
      [],
    ),
  'createPaymentTransaction' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, TransactionStatus],
      [IDL.Nat],
      [],
    ),
  'createTransportBooking' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Int,
        IDL.Nat,
        IDL.Nat,
      ],
      [IDL.Nat],
      [],
    ),
  'createTransportOption' : IDL.Func(
      [
        TransportType,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Vec(IDL.Text),
      ],
      [IDL.Nat],
      [],
    ),
  'deleteHotel' : IDL.Func([IDL.Nat], [], []),
  'deleteTransportOption' : IDL.Func([IDL.Nat], [], []),
  'getAllHotelBookings' : IDL.Func([], [IDL.Vec(HotelBooking)], ['query']),
  'getAllHotels' : IDL.Func([], [IDL.Vec(Hotel)], ['query']),
  'getAllPaymentTransactions' : IDL.Func(
      [],
      [IDL.Vec(PaymentTransaction)],
      ['query'],
    ),
  'getAllTransportBookings' : IDL.Func(
      [],
      [IDL.Vec(TransportBooking)],
      ['query'],
    ),
  'getAllTransportOptions' : IDL.Func(
      [],
      [IDL.Vec(TransportOption)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getHotel' : IDL.Func([IDL.Nat], [IDL.Opt(Hotel)], ['query']),
  'getHotelBooking' : IDL.Func([IDL.Nat], [IDL.Opt(HotelBooking)], ['query']),
  'getPaymentTransactionByBookingId' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(PaymentTransaction)],
      ['query'],
    ),
  'getTransportBooking' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(TransportBooking)],
      ['query'],
    ),
  'getTransportOption' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(TransportOption)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateHotel' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(RoomType),
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
      ],
      [],
      [],
    ),
  'updateHotelBookingPaymentStatus' : IDL.Func(
      [IDL.Nat, TransactionStatus],
      [],
      [],
    ),
  'updateHotelBookingStatus' : IDL.Func([IDL.Nat, BookingStatus], [], []),
  'updateTransportBookingPaymentStatus' : IDL.Func(
      [IDL.Nat, TransactionStatus],
      [],
      [],
    ),
  'updateTransportBookingStatus' : IDL.Func([IDL.Nat, BookingStatus], [], []),
  'updateTransportOption' : IDL.Func(
      [
        IDL.Nat,
        TransportType,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Vec(IDL.Text),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const RoomType = IDL.Record({ 'pricePerNight' : IDL.Nat, 'name' : IDL.Text });
  const TransactionStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'failed' : IDL.Null,
  });
  const TransportType = IDL.Variant({
    'bus' : IDL.Null,
    'car' : IDL.Null,
    'train' : IDL.Null,
    'flight' : IDL.Null,
    'helicopter' : IDL.Null,
    'cruise' : IDL.Null,
  });
  const BookingStatus = IDL.Variant({
    'new' : IDL.Null,
    'cancelled' : IDL.Null,
    'reviewed' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const HotelBooking = IDL.Record({
    'id' : IDL.Nat,
    'status' : BookingStatus,
    'paymentStatus' : TransactionStatus,
    'hotelName' : IDL.Text,
    'pricePerNight' : IDL.Nat,
    'createdAt' : IDL.Int,
    'hotelId' : IDL.Nat,
    'checkInDate' : IDL.Int,
    'guestName' : IDL.Text,
    'guestEmail' : IDL.Text,
    'totalAmount' : IDL.Nat,
    'checkOutDate' : IDL.Int,
    'guestPhone' : IDL.Text,
    'numberOfNights' : IDL.Nat,
    'roomType' : IDL.Text,
  });
  const Hotel = IDL.Record({
    'id' : IDL.Nat,
    'roomTypes' : IDL.Vec(RoomType),
    'photoUrls' : IDL.Vec(IDL.Text),
    'city' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'amenities' : IDL.Vec(IDL.Text),
    'address' : IDL.Text,
  });
  const PaymentTransaction = IDL.Record({
    'id' : IDL.Nat,
    'status' : TransactionStatus,
    'paymentMethod' : IDL.Text,
    'bookingId' : IDL.Nat,
    'timestamp' : IDL.Int,
    'amount' : IDL.Nat,
    'transactionId' : IDL.Text,
  });
  const TransportBooking = IDL.Record({
    'id' : IDL.Nat,
    'status' : BookingStatus,
    'paymentStatus' : TransactionStatus,
    'bookedBy' : IDL.Principal,
    'transportId' : IDL.Nat,
    'city' : IDL.Text,
    'createdAt' : IDL.Int,
    'operatorName' : IDL.Text,
    'passengerName' : IDL.Text,
    'seats' : IDL.Nat,
    'passengerEmail' : IDL.Text,
    'totalAmount' : IDL.Nat,
    'travelDate' : IDL.Int,
    'transportName' : IDL.Text,
    'transportType' : IDL.Text,
    'passengerPhone' : IDL.Text,
    'route' : IDL.Text,
  });
  const TransportOption = IDL.Record({
    'id' : IDL.Nat,
    'photoUrls' : IDL.Vec(IDL.Text),
    'city' : IDL.Text,
    'createdAt' : IDL.Int,
    'operatorName' : IDL.Text,
    'availableSeats' : IDL.Nat,
    'transportType' : TransportType,
    'price' : IDL.Nat,
    'route' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createHotel' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(RoomType),
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
        ],
        [IDL.Nat],
        [],
      ),
    'createHotelBooking' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Int,
          IDL.Int,
          IDL.Nat,
          IDL.Nat,
        ],
        [IDL.Nat],
        [],
      ),
    'createPaymentTransaction' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, TransactionStatus],
        [IDL.Nat],
        [],
      ),
    'createTransportBooking' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Int,
          IDL.Nat,
          IDL.Nat,
        ],
        [IDL.Nat],
        [],
      ),
    'createTransportOption' : IDL.Func(
        [
          TransportType,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Vec(IDL.Text),
        ],
        [IDL.Nat],
        [],
      ),
    'deleteHotel' : IDL.Func([IDL.Nat], [], []),
    'deleteTransportOption' : IDL.Func([IDL.Nat], [], []),
    'getAllHotelBookings' : IDL.Func([], [IDL.Vec(HotelBooking)], ['query']),
    'getAllHotels' : IDL.Func([], [IDL.Vec(Hotel)], ['query']),
    'getAllPaymentTransactions' : IDL.Func(
        [],
        [IDL.Vec(PaymentTransaction)],
        ['query'],
      ),
    'getAllTransportBookings' : IDL.Func(
        [],
        [IDL.Vec(TransportBooking)],
        ['query'],
      ),
    'getAllTransportOptions' : IDL.Func(
        [],
        [IDL.Vec(TransportOption)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getHotel' : IDL.Func([IDL.Nat], [IDL.Opt(Hotel)], ['query']),
    'getHotelBooking' : IDL.Func([IDL.Nat], [IDL.Opt(HotelBooking)], ['query']),
    'getPaymentTransactionByBookingId' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(PaymentTransaction)],
        ['query'],
      ),
    'getTransportBooking' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(TransportBooking)],
        ['query'],
      ),
    'getTransportOption' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(TransportOption)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateHotel' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(RoomType),
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
        ],
        [],
        [],
      ),
    'updateHotelBookingPaymentStatus' : IDL.Func(
        [IDL.Nat, TransactionStatus],
        [],
        [],
      ),
    'updateHotelBookingStatus' : IDL.Func([IDL.Nat, BookingStatus], [], []),
    'updateTransportBookingPaymentStatus' : IDL.Func(
        [IDL.Nat, TransactionStatus],
        [],
        [],
      ),
    'updateTransportBookingStatus' : IDL.Func([IDL.Nat, BookingStatus], [], []),
    'updateTransportOption' : IDL.Func(
        [
          IDL.Nat,
          TransportType,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Vec(IDL.Text),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };