/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type BookingStatus = { 'new' : null } |
  { 'cancelled' : null } |
  { 'reviewed' : null } |
  { 'confirmed' : null };
export interface Hotel {
  'id' : bigint,
  'roomTypes' : Array<RoomType>,
  'photoUrls' : Array<string>,
  'city' : string,
  'name' : string,
  'createdAt' : bigint,
  'description' : string,
  'amenities' : Array<string>,
  'address' : string,
}
export interface HotelBooking {
  'id' : bigint,
  'status' : BookingStatus,
  'paymentStatus' : TransactionStatus,
  'hotelName' : string,
  'pricePerNight' : bigint,
  'createdAt' : bigint,
  'hotelId' : bigint,
  'checkInDate' : bigint,
  'guestName' : string,
  'guestEmail' : string,
  'totalAmount' : bigint,
  'checkOutDate' : bigint,
  'guestPhone' : string,
  'numberOfNights' : bigint,
  'roomType' : string,
}
export interface PaymentTransaction {
  'id' : bigint,
  'status' : TransactionStatus,
  'paymentMethod' : string,
  'bookingId' : bigint,
  'timestamp' : bigint,
  'amount' : bigint,
  'transactionId' : string,
}
export interface RoomType { 'pricePerNight' : bigint, 'name' : string }
export type TransactionStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'failed' : null };
export interface TransportBooking {
  'id' : bigint,
  'status' : BookingStatus,
  'paymentStatus' : TransactionStatus,
  'bookedBy' : Principal,
  'transportId' : bigint,
  'city' : string,
  'createdAt' : bigint,
  'operatorName' : string,
  'passengerName' : string,
  'seats' : bigint,
  'passengerEmail' : string,
  'totalAmount' : bigint,
  'travelDate' : bigint,
  'transportName' : string,
  'transportType' : string,
  'passengerPhone' : string,
  'route' : string,
}
export interface TransportOption {
  'id' : bigint,
  'photoUrls' : Array<string>,
  'city' : string,
  'createdAt' : bigint,
  'operatorName' : string,
  'availableSeats' : bigint,
  'transportType' : TransportType,
  'price' : bigint,
  'route' : string,
}
export type TransportType = { 'bus' : null } |
  { 'car' : null } |
  { 'train' : null } |
  { 'flight' : null } |
  { 'helicopter' : null } |
  { 'cruise' : null };
export interface UserProfile {
  'name' : string,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createHotel' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      Array<RoomType>,
      Array<string>,
      Array<string>,
    ],
    bigint
  >,
  'createHotelBooking' : ActorMethod<
    [
      bigint,
      string,
      string,
      bigint,
      string,
      string,
      string,
      bigint,
      bigint,
      bigint,
      bigint,
    ],
    bigint
  >,
  'createPaymentTransaction' : ActorMethod<
    [string, string, bigint, bigint, TransactionStatus],
    bigint
  >,
  'createTransportBooking' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      bigint,
      bigint,
      bigint,
    ],
    bigint
  >,
  'createTransportOption' : ActorMethod<
    [TransportType, string, string, string, bigint, bigint, Array<string>],
    bigint
  >,
  'deleteHotel' : ActorMethod<[bigint], undefined>,
  'deleteTransportOption' : ActorMethod<[bigint], undefined>,
  'getAllHotelBookings' : ActorMethod<[], Array<HotelBooking>>,
  'getAllHotels' : ActorMethod<[], Array<Hotel>>,
  'getAllPaymentTransactions' : ActorMethod<[], Array<PaymentTransaction>>,
  'getAllTransportBookings' : ActorMethod<[], Array<TransportBooking>>,
  'getAllTransportOptions' : ActorMethod<[], Array<TransportOption>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getHotel' : ActorMethod<[bigint], [] | [Hotel]>,
  'getHotelBooking' : ActorMethod<[bigint], [] | [HotelBooking]>,
  'getPaymentTransactionByBookingId' : ActorMethod<
    [bigint],
    [] | [PaymentTransaction]
  >,
  'getTransportBooking' : ActorMethod<[bigint], [] | [TransportBooking]>,
  'getTransportOption' : ActorMethod<[bigint], [] | [TransportOption]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateHotel' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      string,
      Array<RoomType>,
      Array<string>,
      Array<string>,
    ],
    undefined
  >,
  'updateHotelBookingPaymentStatus' : ActorMethod<
    [bigint, TransactionStatus],
    undefined
  >,
  'updateHotelBookingStatus' : ActorMethod<[bigint, BookingStatus], undefined>,
  'updateTransportBookingPaymentStatus' : ActorMethod<
    [bigint, TransactionStatus],
    undefined
  >,
  'updateTransportBookingStatus' : ActorMethod<
    [bigint, BookingStatus],
    undefined
  >,
  'updateTransportOption' : ActorMethod<
    [
      bigint,
      TransportType,
      string,
      string,
      string,
      bigint,
      bigint,
      Array<string>,
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];