/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface HotelBooking {
    id: bigint;
    status: BookingStatus;
    paymentStatus: TransactionStatus;
    hotelName: string;
    pricePerNight: bigint;
    createdAt: bigint;
    hotelId: bigint;
    checkInDate: bigint;
    guestName: string;
    guestEmail: string;
    totalAmount: bigint;
    checkOutDate: bigint;
    guestPhone: string;
    numberOfNights: bigint;
    roomType: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface RoomType {
    pricePerNight: bigint;
    name: string;
}
export interface PaymentTransaction {
    id: bigint;
    status: TransactionStatus;
    paymentMethod: string;
    bookingId: bigint;
    timestamp: bigint;
    amount: bigint;
    transactionId: string;
}
export interface TransportOption {
    id: bigint;
    photoUrls: Array<string>;
    city: string;
    createdAt: bigint;
    operatorName: string;
    availableSeats: bigint;
    transportType: TransportType;
    price: bigint;
    route: string;
}
export interface Hotel {
    id: bigint;
    roomTypes: Array<RoomType>;
    photoUrls: Array<string>;
    city: string;
    name: string;
    createdAt: bigint;
    description: string;
    amenities: Array<string>;
    address: string;
}
export interface TransportBooking {
    id: bigint;
    status: BookingStatus;
    paymentStatus: TransactionStatus;
    bookedBy: Principal;
    transportId: bigint;
    city: string;
    createdAt: bigint;
    operatorName: string;
    passengerName: string;
    seats: bigint;
    passengerEmail: string;
    totalAmount: bigint;
    travelDate: bigint;
    transportName: string;
    transportType: string;
    passengerPhone: string;
    route: string;
}
export interface UserProfile {
    name: string;
    email: string;
    phone: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum BookingStatus {
    new_ = "new",
    cancelled = "cancelled",
    reviewed = "reviewed",
    confirmed = "confirmed"
}
export enum TransactionStatus {
    pending = "pending",
    completed = "completed",
    failed = "failed"
}
export enum TransportType {
    bus = "bus",
    car = "car",
    train = "train",
    flight = "flight",
    helicopter = "helicopter",
    cruise = "cruise"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createHotel(name: string, city: string, address: string, description: string, roomTypes: Array<RoomType>, amenities: Array<string>, photoUrls: Array<string>): Promise<bigint>;
    createHotelBooking(hotelId: bigint, hotelName: string, roomType: string, pricePerNight: bigint, guestName: string, guestPhone: string, guestEmail: string, checkInDate: bigint, checkOutDate: bigint, numberOfNights: bigint, totalAmount: bigint): Promise<bigint>;
    createPaymentTransaction(transactionId: string, paymentMethod: string, amount: bigint, bookingId: bigint, status: TransactionStatus): Promise<bigint>;
    createTransportBooking(transportId: bigint, transportName: string, transportType: string, operatorName: string, route: string, passengerName: string, passengerPhone: string, passengerEmail: string, city: string, travelDate: bigint, seats: bigint, totalAmount: bigint): Promise<bigint>;
    createTransportOption(transportType: TransportType, operatorName: string, route: string, city: string, price: bigint, availableSeats: bigint, photoUrls: Array<string>): Promise<bigint>;
    deleteHotel(id: bigint): Promise<void>;
    deleteTransportOption(id: bigint): Promise<void>;
    getAllHotelBookings(): Promise<Array<HotelBooking>>;
    getAllHotels(): Promise<Array<Hotel>>;
    getAllPaymentTransactions(): Promise<Array<PaymentTransaction>>;
    getAllTransportBookings(): Promise<Array<TransportBooking>>;
    getAllTransportOptions(): Promise<Array<TransportOption>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getHotel(id: bigint): Promise<Hotel | null>;
    getHotelBooking(id: bigint): Promise<HotelBooking | null>;
    getPaymentTransactionByBookingId(bookingId: bigint): Promise<PaymentTransaction | null>;
    getTransportBooking(id: bigint): Promise<TransportBooking | null>;
    getTransportOption(id: bigint): Promise<TransportOption | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateHotel(id: bigint, name: string, city: string, address: string, description: string, roomTypes: Array<RoomType>, amenities: Array<string>, photoUrls: Array<string>): Promise<void>;
    updateHotelBookingPaymentStatus(id: bigint, paymentStatus: TransactionStatus): Promise<void>;
    updateHotelBookingStatus(id: bigint, status: BookingStatus): Promise<void>;
    updateTransportBookingPaymentStatus(id: bigint, paymentStatus: TransactionStatus): Promise<void>;
    updateTransportBookingStatus(id: bigint, status: BookingStatus): Promise<void>;
    updateTransportOption(id: bigint, transportType: TransportType, operatorName: string, route: string, city: string, price: bigint, availableSeats: bigint, photoUrls: Array<string>): Promise<void>;
}
import type { BookingStatus as _BookingStatus, Hotel as _Hotel, HotelBooking as _HotelBooking, PaymentTransaction as _PaymentTransaction, TransactionStatus as _TransactionStatus, TransportBooking as _TransportBooking, TransportOption as _TransportOption, TransportType as _TransportType, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createHotel(arg0: string, arg1: string, arg2: string, arg3: string, arg4: Array<RoomType>, arg5: Array<string>, arg6: Array<string>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createHotel(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createHotel(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async createHotelBooking(arg0: bigint, arg1: string, arg2: string, arg3: bigint, arg4: string, arg5: string, arg6: string, arg7: bigint, arg8: bigint, arg9: bigint, arg10: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createHotelBooking(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createHotelBooking(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
            return result;
        }
    }
    async createPaymentTransaction(arg0: string, arg1: string, arg2: bigint, arg3: bigint, arg4: TransactionStatus): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createPaymentTransaction(arg0, arg1, arg2, arg3, to_candid_TransactionStatus_n10(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPaymentTransaction(arg0, arg1, arg2, arg3, to_candid_TransactionStatus_n10(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async createTransportBooking(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string, arg7: string, arg8: string, arg9: bigint, arg10: bigint, arg11: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createTransportBooking(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTransportBooking(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11);
            return result;
        }
    }
    async createTransportOption(arg0: TransportType, arg1: string, arg2: string, arg3: string, arg4: bigint, arg5: bigint, arg6: Array<string>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createTransportOption(to_candid_TransportType_n12(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTransportOption(to_candid_TransportType_n12(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async deleteHotel(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteHotel(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteHotel(arg0);
            return result;
        }
    }
    async deleteTransportOption(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTransportOption(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTransportOption(arg0);
            return result;
        }
    }
    async getAllHotelBookings(): Promise<Array<HotelBooking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllHotelBookings();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllHotelBookings();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllHotels(): Promise<Array<Hotel>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllHotels();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllHotels();
            return result;
        }
    }
    async getAllPaymentTransactions(): Promise<Array<PaymentTransaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPaymentTransactions();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPaymentTransactions();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTransportBookings(): Promise<Array<TransportBooking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTransportBookings();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTransportBookings();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTransportOptions(): Promise<Array<TransportOption>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTransportOptions();
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTransportOptions();
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHotel(arg0: bigint): Promise<Hotel | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getHotel(arg0);
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHotel(arg0);
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHotelBooking(arg0: bigint): Promise<HotelBooking | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getHotelBooking(arg0);
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHotelBooking(arg0);
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPaymentTransactionByBookingId(arg0: bigint): Promise<PaymentTransaction | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPaymentTransactionByBookingId(arg0);
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPaymentTransactionByBookingId(arg0);
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTransportBooking(arg0: bigint): Promise<TransportBooking | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransportBooking(arg0);
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransportBooking(arg0);
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTransportOption(arg0: bigint): Promise<TransportOption | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransportOption(arg0);
                return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransportOption(arg0);
            return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateHotel(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: Array<RoomType>, arg6: Array<string>, arg7: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateHotel(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateHotel(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async updateHotelBookingPaymentStatus(arg0: bigint, arg1: TransactionStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateHotelBookingPaymentStatus(arg0, to_candid_TransactionStatus_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateHotelBookingPaymentStatus(arg0, to_candid_TransactionStatus_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateHotelBookingStatus(arg0: bigint, arg1: BookingStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateHotelBookingStatus(arg0, to_candid_BookingStatus_n40(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateHotelBookingStatus(arg0, to_candid_BookingStatus_n40(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateTransportBookingPaymentStatus(arg0: bigint, arg1: TransactionStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTransportBookingPaymentStatus(arg0, to_candid_TransactionStatus_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTransportBookingPaymentStatus(arg0, to_candid_TransactionStatus_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateTransportBookingStatus(arg0: bigint, arg1: BookingStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTransportBookingStatus(arg0, to_candid_BookingStatus_n40(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTransportBookingStatus(arg0, to_candid_BookingStatus_n40(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateTransportOption(arg0: bigint, arg1: TransportType, arg2: string, arg3: string, arg4: string, arg5: bigint, arg6: bigint, arg7: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTransportOption(arg0, to_candid_TransportType_n12(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTransportOption(arg0, to_candid_TransportType_n12(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
}
function from_candid_BookingStatus_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingStatus): BookingStatus {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_HotelBooking_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HotelBooking): HotelBooking {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentTransaction_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentTransaction): PaymentTransaction {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_TransactionStatus_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionStatus): TransactionStatus {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_TransportBooking_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransportBooking): TransportBooking {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_TransportOption_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransportOption): TransportOption {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_TransportType_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransportType): TransportType {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Hotel]): Hotel | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_HotelBooking]): HotelBooking | null {
    return value.length === 0 ? null : from_candid_HotelBooking_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PaymentTransaction]): PaymentTransaction | null {
    return value.length === 0 ? null : from_candid_PaymentTransaction_n22(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TransportBooking]): TransportBooking | null {
    return value.length === 0 ? null : from_candid_TransportBooking_n25(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TransportOption]): TransportOption | null {
    return value.length === 0 ? null : from_candid_TransportOption_n28(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _BookingStatus;
    paymentStatus: _TransactionStatus;
    hotelName: string;
    pricePerNight: bigint;
    createdAt: bigint;
    hotelId: bigint;
    checkInDate: bigint;
    guestName: string;
    guestEmail: string;
    totalAmount: bigint;
    checkOutDate: bigint;
    guestPhone: string;
    numberOfNights: bigint;
    roomType: string;
}): {
    id: bigint;
    status: BookingStatus;
    paymentStatus: TransactionStatus;
    hotelName: string;
    pricePerNight: bigint;
    createdAt: bigint;
    hotelId: bigint;
    checkInDate: bigint;
    guestName: string;
    guestEmail: string;
    totalAmount: bigint;
    checkOutDate: bigint;
    guestPhone: string;
    numberOfNights: bigint;
    roomType: string;
} {
    return {
        id: value.id,
        status: from_candid_BookingStatus_n17(_uploadFile, _downloadFile, value.status),
        paymentStatus: from_candid_TransactionStatus_n19(_uploadFile, _downloadFile, value.paymentStatus),
        hotelName: value.hotelName,
        pricePerNight: value.pricePerNight,
        createdAt: value.createdAt,
        hotelId: value.hotelId,
        checkInDate: value.checkInDate,
        guestName: value.guestName,
        guestEmail: value.guestEmail,
        totalAmount: value.totalAmount,
        checkOutDate: value.checkOutDate,
        guestPhone: value.guestPhone,
        numberOfNights: value.numberOfNights,
        roomType: value.roomType
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _TransactionStatus;
    paymentMethod: string;
    bookingId: bigint;
    timestamp: bigint;
    amount: bigint;
    transactionId: string;
}): {
    id: bigint;
    status: TransactionStatus;
    paymentMethod: string;
    bookingId: bigint;
    timestamp: bigint;
    amount: bigint;
    transactionId: string;
} {
    return {
        id: value.id,
        status: from_candid_TransactionStatus_n19(_uploadFile, _downloadFile, value.status),
        paymentMethod: value.paymentMethod,
        bookingId: value.bookingId,
        timestamp: value.timestamp,
        amount: value.amount,
        transactionId: value.transactionId
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _BookingStatus;
    paymentStatus: _TransactionStatus;
    bookedBy: Principal;
    transportId: bigint;
    city: string;
    createdAt: bigint;
    operatorName: string;
    passengerName: string;
    seats: bigint;
    passengerEmail: string;
    totalAmount: bigint;
    travelDate: bigint;
    transportName: string;
    transportType: string;
    passengerPhone: string;
    route: string;
}): {
    id: bigint;
    status: BookingStatus;
    paymentStatus: TransactionStatus;
    bookedBy: Principal;
    transportId: bigint;
    city: string;
    createdAt: bigint;
    operatorName: string;
    passengerName: string;
    seats: bigint;
    passengerEmail: string;
    totalAmount: bigint;
    travelDate: bigint;
    transportName: string;
    transportType: string;
    passengerPhone: string;
    route: string;
} {
    return {
        id: value.id,
        status: from_candid_BookingStatus_n17(_uploadFile, _downloadFile, value.status),
        paymentStatus: from_candid_TransactionStatus_n19(_uploadFile, _downloadFile, value.paymentStatus),
        bookedBy: value.bookedBy,
        transportId: value.transportId,
        city: value.city,
        createdAt: value.createdAt,
        operatorName: value.operatorName,
        passengerName: value.passengerName,
        seats: value.seats,
        passengerEmail: value.passengerEmail,
        totalAmount: value.totalAmount,
        travelDate: value.travelDate,
        transportName: value.transportName,
        transportType: value.transportType,
        passengerPhone: value.passengerPhone,
        route: value.route
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    photoUrls: Array<string>;
    city: string;
    createdAt: bigint;
    operatorName: string;
    availableSeats: bigint;
    transportType: _TransportType;
    price: bigint;
    route: string;
}): {
    id: bigint;
    photoUrls: Array<string>;
    city: string;
    createdAt: bigint;
    operatorName: string;
    availableSeats: bigint;
    transportType: TransportType;
    price: bigint;
    route: string;
} {
    return {
        id: value.id,
        photoUrls: value.photoUrls,
        city: value.city,
        createdAt: value.createdAt,
        operatorName: value.operatorName,
        availableSeats: value.availableSeats,
        transportType: from_candid_TransportType_n30(_uploadFile, _downloadFile, value.transportType),
        price: value.price,
        route: value.route
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    new: null;
} | {
    cancelled: null;
} | {
    reviewed: null;
} | {
    confirmed: null;
}): BookingStatus {
    return "new" in value ? BookingStatus.new : "cancelled" in value ? BookingStatus.cancelled : "reviewed" in value ? BookingStatus.reviewed : "confirmed" in value ? BookingStatus.confirmed : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    failed: null;
}): TransactionStatus {
    return "pending" in value ? TransactionStatus.pending : "completed" in value ? TransactionStatus.completed : "failed" in value ? TransactionStatus.failed : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bus: null;
} | {
    car: null;
} | {
    train: null;
} | {
    flight: null;
} | {
    helicopter: null;
} | {
    cruise: null;
}): TransportType {
    return "bus" in value ? TransportType.bus : "car" in value ? TransportType.car : "train" in value ? TransportType.train : "flight" in value ? TransportType.flight : "helicopter" in value ? TransportType.helicopter : "cruise" in value ? TransportType.cruise : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_HotelBooking>): Array<HotelBooking> {
    return value.map((x)=>from_candid_HotelBooking_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PaymentTransaction>): Array<PaymentTransaction> {
    return value.map((x)=>from_candid_PaymentTransaction_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TransportBooking>): Array<TransportBooking> {
    return value.map((x)=>from_candid_TransportBooking_n25(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TransportOption>): Array<TransportOption> {
    return value.map((x)=>from_candid_TransportOption_n28(_uploadFile, _downloadFile, x));
}
function to_candid_BookingStatus_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus): _BookingStatus {
    return to_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function to_candid_TransactionStatus_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionStatus): _TransactionStatus {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_TransportType_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransportType): _TransportType {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionStatus): {
    pending: null;
} | {
    completed: null;
} | {
    failed: null;
} {
    return value == TransactionStatus.pending ? {
        pending: null
    } : value == TransactionStatus.completed ? {
        completed: null
    } : value == TransactionStatus.failed ? {
        failed: null
    } : value;
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransportType): {
    bus: null;
} | {
    car: null;
} | {
    train: null;
} | {
    flight: null;
} | {
    helicopter: null;
} | {
    cruise: null;
} {
    return value == TransportType.bus ? {
        bus: null
    } : value == TransportType.car ? {
        car: null
    } : value == TransportType.train ? {
        train: null
    } : value == TransportType.flight ? {
        flight: null
    } : value == TransportType.helicopter ? {
        helicopter: null
    } : value == TransportType.cruise ? {
        cruise: null
    } : value;
}
function to_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus): {
    new: null;
} | {
    cancelled: null;
} | {
    reviewed: null;
} | {
    confirmed: null;
} {
    return value == BookingStatus.new ? {
        new_: null
    } : value == BookingStatus.cancelled ? {
        cancelled: null
    } : value == BookingStatus.reviewed ? {
        reviewed: null
    } : value == BookingStatus.confirmed ? {
        confirmed: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
